name = "BiasedBisect"
defaultTargets = ["BiasedBisect"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
linter.flexible = true
linter.hashCommand = true
linter.oldObtain = true
linter.style.cases = true
linter.style.cdot = true
linter.style.docString = true
linter.style.dollarSyntax = true
linter.style.header = true
linter.style.lambdaSyntax = true
linter.style.maxHeartbeats = true
linter.style.missingEnd = true
linter.style.multiGoal = true
linter.style.openClassical = true
linter.style.refine = true
linter.style.setOption = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[require]]
scope = "leanprover"
name = "doc-gen4"

[[lean_lib]]
name = "BiasedBisect"

[[lean_exe]]
name = "BbCalculator"